openapi: 3.0.1
info:
  title: integrations-api
  description: API Definition of integrations-api
  version: 1.0.0
servers:
- url: http://localhost:8290/integrations-api
paths:
  /enhance_and_add_to_purchase_q:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /validate_iterate_add_purchase_to_kafka:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /test:
    get:
      responses:
        default:
          description: Default response
  /test-be:
    get:
      responses:
        default:
          description: Default response
  /add_to_purchase:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
